version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=postgresql://aaa01:xulfagRmNdyq4iBXqQnZ2EnGfoPngB5M@dpg-cvi99j8gjchc73fajaqg-a/muscle_training_db_xfz0
      - FLASK_APP=app
      - FLASK_ENV=development
      - SECRET_KEY=your_secret_key
    depends_on:
      - postgres
    volumes:
      - .:/app

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=aaa01
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=muscle_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: